"use client";

import React from "react";
import { 
  PiThumbsUpDuotone,
  PiChatCircleTextDuotone,
  PiShareNetworkDuotone,
  PiBookmarkSimpleDuotone,
  PiLightningDuotone,
  PiCodeDuotone,
  PiPenNibDuotone,
  PiPaletteDuotone,
  PiCalculatorDuotone,
  PiUsersDuotone,
  PiHeartDuotone,
  PiTrophyDuotone,
  PiMedalDuotone,
  PiTargetDuotone,
  PiFireDuotone,
  PiSneakerDuotone,
  PiSparkleDuotone,
  PiFlagDuotone,
  PiRocketLaunchDuotone,
  PiBugDuotone,
  PiFlaskDuotone,
  PiCakeDuotone,
  PiStarDuotone,
  PiHashDuotone,
  PiCrownDuotone,
  PiGraduationCapDuotone
} from "react-icons/pi";

export const PREMIUM_ICONS_MAP: Record<string, React.ElementType> = {
  thumbs_up: PiThumbsUpDuotone,
  message_circle: PiChatCircleTextDuotone,
  share_2: PiShareNetworkDuotone,
  bookmark: PiBookmarkSimpleDuotone,
  zap: PiLightningDuotone,
  code_2: PiCodeDuotone,
  pen_tool: PiPenNibDuotone,
  palette: PiPaletteDuotone,
  calculator: PiCalculatorDuotone,
  users: PiUsersDuotone,
  heart: PiHeartDuotone,
  trophy: PiTrophyDuotone,
  award: PiMedalDuotone,
  target: PiTargetDuotone,
  flame: PiFireDuotone,
  footprints: PiSneakerDuotone,
  sparkles: PiSparkleDuotone,
  flag: PiFlagDuotone,
  rocket: PiRocketLaunchDuotone,
  bug: PiBugDuotone,
  flask: PiFlaskDuotone,
  cake: PiCakeDuotone,
  star: PiStarDuotone,
  hash: PiHashDuotone,
  crown: PiCrownDuotone,
  graduation_cap: PiGraduationCapDuotone,
  medal: PiMedalDuotone,
  default: PiSparkleDuotone,
};
