-- Add coins_count to projects table
ALTER TABLE projects ADD COLUMN IF NOT EXISTS coins_count integer DEFAULT 0 NOT NULL;

-- Create project_coins table to track who tipped which project
CREATE TABLE IF NOT EXISTS project_coins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    project_id bigint REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
    amount integer NOT NULL CHECK (amount > 0),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Index for fast queries
CREATE INDEX IF NOT EXISTS idx_project_coins_user_id ON project_coins(user_id);
CREATE INDEX IF NOT EXISTS idx_project_coins_project_id ON project_coins(project_id);
CREATE INDEX IF NOT EXISTS idx_project_coins_user_project ON project_coins(user_id, project_id);

-- Enable RLS
ALTER TABLE project_coins ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view all project coins"
    ON project_coins FOR SELECT
    USING (true);

-- Insert handled via RPC for atomicity, no direct insert policy needed for users typically,
-- but adding it for super admin or RPC bypassing RLS if needed.
-- Security definer RPC will bypass RLS.

-- RPC function to tip a project
CREATE OR REPLACE FUNCTION tip_project(p_project_id bigint, p_amount integer)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_giver_id uuid;
    v_author_id uuid;
    v_giver_coins integer;
    v_user_total_tipped integer;
BEGIN
    -- 1. Get current user ID
    v_giver_id := auth.uid();
    IF v_giver_id IS NULL THEN
        RETURN json_build_object('success', false, 'error', 'Not authenticated');
    END IF;

    -- 2. Validate amount
    IF p_amount <= 0 THEN
         RETURN json_build_object('success', false, 'error', 'Amount must be greater than 0');
    END IF;

    -- 3. Check if user already tipped too much (e.g., max 2 coins per project)
    SELECT COALESCE(SUM(amount), 0) INTO v_user_total_tipped
    FROM project_coins
    WHERE user_id = v_giver_id AND project_id = p_project_id;
    
    IF v_user_total_tipped + p_amount > 2 THEN
         RETURN json_build_object('success', false, 'error', 'Cannot tip more than 2 coins per project');
    END IF;

    -- 4. Get project author and lock project row
    SELECT author_id INTO v_author_id
    FROM projects
    WHERE id = p_project_id
    FOR UPDATE;

    IF v_author_id IS NULL THEN
        RETURN json_build_object('success', false, 'error', 'Project not found');
    END IF;

    -- Cannot tip own project
    IF v_giver_id = v_author_id THEN
         RETURN json_build_object('success', false, 'error', 'Cannot tip your own project');
    END IF;

    -- 5. Lock and check giver's balance
    SELECT coins INTO v_giver_coins
    FROM profiles
    WHERE id = v_giver_id
    FOR UPDATE;

    IF v_giver_coins < p_amount THEN
        RETURN json_build_object('success', false, 'error', 'Insufficient coins');
    END IF;

    -- 6. Execute updates
    
    -- Deduct from giver
    UPDATE profiles
    SET coins = coins - p_amount
    WHERE id = v_giver_id;

    -- Add to author
    UPDATE profiles
    SET coins = coins + p_amount
    WHERE id = v_author_id;

    -- Increment project coins count
    UPDATE projects
    SET coins_count = coins_count + p_amount
    WHERE id = p_project_id;

    -- Record transaction
    INSERT INTO project_coins (user_id, project_id, amount)
    VALUES (v_giver_id, p_project_id, p_amount);

    -- Record action logs
    INSERT INTO coin_logs (user_id, amount, action_type, resource_id)
    VALUES (v_giver_id, -p_amount, 'tip_project', p_project_id::text);

    INSERT INTO coin_logs (user_id, amount, action_type, resource_id)
    VALUES (v_author_id, p_amount, 'receive_tip', p_project_id::text);

    RETURN json_build_object('success', true, 'new_project_coins', (SELECT coins_count FROM projects WHERE id = p_project_id));
    
EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'error', SQLERRM);
END;
$$;
